all check: linenoise.o

install install-strip uninstall check installcheck dist:

clean distclean maintainer-clean:
	rm -f linenoise.o

.PHONY: all install install-strip uninstall check installcheck dist clean distclean maintainer-clean

